name: Create release artifact

on: workflow_call

permissions: read-all

jobs:
  create-release:
    name: Create release artifact step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm build
      - run: mkdir artifacts
      - run: |
          tar -czf artifacts/release.zip dist/

